
import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Urban Explorer Jacket',
    description:
      'A versatile and stylish jacket designed for the modern urban explorer. Water-resistant fabric with a comfortable inner lining.',
    price: 6999,
    images: [
      'https://picsum.photos/seed/jacket1/800/1000',
      'https://picsum.photos/seed/jacket2/800/1000',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Obsidian Black', 'Forest Green'],
    category: 'Outerwear',
    dataAiHint: 'mens jacket',
  },
  {
    id: '2',
    name: 'Flowy Linen Trousers',
    description:
      'Lightweight and breathable linen trousers, perfect for warm weather. Features a relaxed fit and an elasticated waistband for ultimate comfort.',
    price: 2499,
    images: [
      'https://picsum.photos/seed/trousers1/800/1000',
      'https://picsum.photos/seed/trousers2/800/1000',
    ],
    sizes: ['S', 'M', 'L'],
    colors: ['Beige', 'White', 'Navy'],
    category: 'Trousers',
    dataAiHint: 'womens trousers',
  },
  {
    id: '3',
    name: 'Classic Oxford Shirt',
    description:
      'A timeless wardrobe staple. This Oxford shirt is made from 100% premium cotton for a soft feel and a sharp look.',
    price: 1799,
    images: [
      'https://picsum.photos/seed/shirt1/800/1000',
      'https://picsum.photos/seed/shirt2/800/1000',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sky Blue', 'White'],
    category: 'Shirts',
    dataAiHint: 'mens shirt',
  },
  {
    id: '4',
    name: 'Minimalist Leather Tote',
    description:
      'Crafted from genuine Italian leather, this tote bag combines functionality with minimalist elegance. Spacious enough for your daily essentials.',
    price: 7999,
    images: [
      'https://picsum.photos/seed/tote1/800/1000',
      'https://picsum.photos/seed/tote2/800/1000',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Cognac'],
    category: 'Accessories',
    dataAiHint: 'leather tote',
  },
  {
    id: '5',
    name: 'Cashmere Blend Scarf',
    description:
      'Stay warm and stylish with this incredibly soft cashmere blend scarf. The perfect accessory for chilly days.',
    price: 2999,
    images: [
      'https://picsum.photos/seed/scarf1/800/1000',
      'https://picsum.photos/seed/scarf2/800/1000',
    ],
    sizes: ['One Size'],
    colors: ['Heather Grey', 'Charcoal'],
    category: 'Accessories',
    dataAiHint: 'cashmere scarf',
  },
  {
    id: '6',
    name: 'Tailored Wool Blazer',
    description:
      'A beautifully tailored single-breasted blazer made from fine Italian wool. Fully lined with a structured shoulder for a sharp silhouette.',
    price: 12999,
    images: [
      'https://picsum.photos/seed/blazer1/800/1000',
      'https://picsum.photos/seed/blazer2/800/1000',
    ],
    sizes: ['38R', '40R', '42R', '44R'],
    colors: ['Charcoal Grey', 'Navy Blue'],
    category: 'Outerwear',
    dataAiHint: 'womens blazer',
  },
  {
    id: '7',
    name: 'Ribbed Knit Sweater',
    description:
      'A cozy and chic ribbed knit sweater with a mock neck design. Made from a soft merino wool blend.',
    price: 4499,
    images: [
      'https://picsum.photos/seed/sweater1/800/1000',
      'https://picsum.photos/seed/sweater2/800/1000',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Cream', 'Black'],
    category: 'Knitwear',
    dataAiHint: 'womens sweater',
  },
  {
    id: '8',
    name: 'Leather Ankle Boots',
    description:
      'Versatile and comfortable, these ankle boots are crafted from smooth leather and feature a sturdy block heel and side zip closure.',
    price: 6999,
    images: [
      'https://picsum.photos/seed/boots1/800/1000',
      'https://picsum.photos/seed/boots2/800/1000',
    ],
    sizes: ['6', '7', '8', '9', '10'],
    colors: ['Black', 'Brown'],
    category: 'Shoes',
    dataAiHint: 'leather boots',
  },
  {
    id: '9',
    name: 'Classic Leather Belt',
    description: 'A timeless leather belt to complete any outfit.',
    price: 49,
    images: [
      'https://picsum.photos/seed/belt1/800/1000',
      'https://picsum.photos/seed/belt2/800/1000',
    ],
    sizes: ['32', '34', '36', '38'],
    colors: ['Black', 'Brown'],
    category: 'Accessories',
    dataAiHint: 'leather belt',
  },
  {
    id: '10',
    name: 'Cotton Ankle Socks (3-Pack)',
    description: 'Comfortable and breathable cotton socks for everyday wear.',
    price: 39,
    images: [
      'https://picsum.photos/seed/socks1/800/1000',
      'https://picsum.photos/seed/socks2/800/1000',
    ],
    sizes: ['One Size'],
    colors: ['White', 'Black', 'Grey'],
    category: 'Accessories',
    dataAiHint: 'cotton socks',
  },
  {
    id: '11',
    name: 'Graphic Print T-Shirt',
    description: 'A soft cotton t-shirt with a unique graphic print. Perfect for a casual, expressive look.',
    price: 999,
    images: ['https://picsum.photos/seed/tshirt1/800/1000'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Washed Black', 'White'],
    category: 'T-Shirts',
    dataAiHint: 'graphic t-shirt',
  },
  {
    id: '12',
    name: 'Slim Fit Chinos',
    description: 'Classic slim-fit chinos crafted from comfortable stretch cotton. A versatile staple for any wardrobe.',
    price: 2499,
    images: ['https://picsum.photos/seed/chinos1/800/1000'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Khaki', 'Navy'],
    category: 'Trousers',
    dataAiHint: 'mens chinos',
  },
  {
    id: '13',
    name: 'Vintage Denim Jacket',
    description: 'A timeless denim jacket with a vintage wash and classic detailing. Built to last and gets better with every wear.',
    price: 5999,
    images: ['https://picsum.photos/seed/denimjacket1/800/1000'],
    sizes: ['S', 'M', 'L'],
    colors: ['Mid Blue'],
    category: 'Outerwear',
    dataAiHint: 'denim jacket',
  },
   {
    id: '14',
    name: 'Silk Blend Blouse',
    description: 'An elegant blouse made from a luxurious silk blend. Features a delicate drape and a subtle sheen.',
    price: 3499,
    images: ['https://picsum.photos/seed/blouse1/800/1000'],
    sizes: ['XS', 'S', 'M'],
    colors: ['Ivory', 'Blush Pink'],
    category: 'Shirts',
    dataAiHint: 'silk blouse',
  },
  {
    id: '15',
    name: 'Everyday Crewneck T-Shirt',
    description: 'The perfect crewneck t-shirt, made from ultra-soft pima cotton for incredible comfort.',
    price: 1199,
    images: ['https://picsum.photos/seed/tshirt2/800/1000'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Black', 'Heather Grey'],
    category: 'T-Shirts',
    dataAiHint: 'mens t-shirt',
  },
  {
    id: '16',
    name: 'Chronograph Steel Watch',
    description: 'A sophisticated chronograph watch with a stainless steel strap and a bold black dial. Perfect for both formal and casual occasions.',
    price: 14999,
    images: ['https://picsum.photos/seed/watch1/800/1000'],
    sizes: ['One Size'],
    colors: ['Silver/Black'],
    category: 'Watches',
    dataAiHint: 'steel watch',
  },
  {
    id: '17',
    name: 'Minimalist Leather Watch',
    description: 'A sleek and modern watch featuring a genuine leather strap and a clean, minimalist white dial. Understated elegance.',
    price: 8999,
    images: ['https://picsum.photos/seed/watch2/800/1000'],
    sizes: ['One Size'],
    colors: ['Brown/White', 'Black/White'],
    category: 'Watches',
    dataAiHint: 'leather watch',
  },
  {
    id: '18',
    name: 'Odyssey Automatic Watch',
    description: 'A statement timepiece with automatic movement, exposed gears, and a durable silicone strap. For the bold and adventurous.',
    price: 19999,
    images: ['https://picsum.photos/seed/watch3/800/1000'],
    sizes: ['One Size'],
    colors: ['Black/Rose Gold'],
    category: 'Watches',
    dataAiHint: 'automatic watch',
  },
];

export const shopTheLookItems = {
  main: {
    image: 'https://picsum.photos/seed/lookmain/800/1200',
    dataAiHint: 'fashion outfit',
  },
  items: [products[5], products[1], products[7]],
};
